spring:
  profiles:
    active: local
 
---        
spring:
   profiles: local
   jpa:
      properties.hibernate.jdbc.lob.non_contextual_creation: true
      show-sql: true
      hibernate:
         ddl-auto: create
      database-platform: org.hibernate.dialect.PostgreSQLDialect
   datasource:
      url: jdbc:postgresql://pellefant.db.elephantsql.com:5432/qvyicnfy
      username: qvyicnfy
      password: tPBLJ_TLnDS5PElKY619DDqP63CtEwEm
   
---        
spring:
   profiles: cloud
   jpa:
      show-sql: true
      hibernate:
         ddl-auto: create
      database-platform: org.hibernate.dialect.PostgreSQLDialect
   datasource:
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://pellefant.db.elephantsql.com:5432/qvyicnfy
      username: qvyicnfy
      password: tPBLJ_TLnDS5PElKY619DDqP63CtEwEm
